#服务配置
server:
  port: 9005
  servlet:
    context-path: /trade

#spring配置
spring:
  application:
    name: carbon-trade #指定服务名
  main:
    allow-circular-references: true
  profiles:
    # 本地运行使用dev，打包时使用test
    active: test
    include: sentinel  # 包含 Sentinel 配置
#    active: test

# 禁用 Swagger/Springfox 相关配置
springfox:
  documentation:
    enabled: false

  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

# 设置 feign 超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000