rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: carbon-mq-producer  # 必须配置，任意合法名称均可（如服务名+producer）
    send-message-timeout: 300000  # 可选，超时时间

#spring配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/carbon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
