#服务配置
server:
  port: 9091

#spring配置
spring:
  #1.应用配置
  main:
    allow-circular-references: true
    web-application-type: reactive # 强制使用 WebFlux
    allow-bean-definition-overriding: true # 允许Bean覆盖
  profiles:
    # 本地运行使用dev，打包时使用test
#        active: dev
    active: test
  application:
    name: carbon-gate #指定服务名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    deserialization:
      fail-on-unknown-properties: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authCenter
          uri: lb://carbon-auth
          predicates:
            - Path=/authCenter/**
        - id: system
          uri: lb://carbon-system
          predicates:
            - Path=/system/**
        - id: assets
          uri: lb://carbon-assets
          predicates:
            - Path=/assets/**
        - id: trade
          uri: lb://carbon-trade
          predicates:
            - Path=/trade/**
      # CORS 全局配置 - 使用application.yml配置，移除过滤器中的重复配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      # HTTP 超时配置
      httpclient:
        connect-timeout: 30000
        response-timeout: 30000

    # Sentinel 配置
    sentinel:
      enabled: true
      # Sentinel Dashboard 配置
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      # 饥饿加载，应用启动时即加载规则
      eager: true
      # Nacos 数据源配置
      datasource:
        # 流控规则数据源
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: carbon-gate-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        # 降级规则数据源
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: carbon-gate-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
        # 网关限流规则数据源
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: carbon-gate-gw-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow

# 设置 feign 超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000

# 负载均衡配置
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000

# 暂时注释掉接口文档配置
#knife4j:
#  enableAggregation: true
#  nacos:
#    routes:
#      - name: 认证中心
#        serviceName: carbon-auth
#        location: /authCenter/v2/api-docs?group=default
#        servicePath: /
#      - name: 系统服务
#        serviceName: carbon-system
#        location: /system/v2/api-docs?group=default
#        servicePath: /
#      - name: 资产服务
#        serviceName: carbon-assets
#        location: /assets/v2/api-docs?group=default
#        servicePath: /
#      - name: 交易服务
#        serviceName: carbon-trade
#        location: /trade/v2/api-docs?group=default
#        servicePath: /

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.carbon.gate: DEBUG
